// Five demo personas that drive the login page (wireframe s01) and the portal
// shells until real Supabase auth is wired up. See the single-file prototype
// for the source of these personas — they must stay consistent.

export const DEMO_USERS = {
  agency: {
    role: "agency",
    email: "alex@brightagency.com.au",
    name: "Alex Johnson",
    company: "Bright Agency Co.",
    icon: "🏢",
    accent: "teal",
    type: "Agency Partner",
    desc: "Order for clients, track profit, manage white-label portal delivery.",
    loginTitle: "Agency Portal",
    loginSub: "Bright Agency Co. · Full access account",
    cta: "Sign in to Agency Portal →",
    home: "/agency/dashboard",
  },
  client: {
    role: "agency_client",
    email: "sarah@coastalrealty.com.au",
    name: "Sarah Mitchell",
    company: "Coastal Realty",
    icon: "👤",
    accent: "#7c87f5",
    type: "Agency Client",
    desc: "Client of Bright Agency — track projects, approve posts and designs.",
    loginTitle: "Client Portal",
    loginSub: "Coastal Realty · Bright Agency Co. white-label",
    cta: "Sign in to Client Portal →",
    home: "/portal/bright-agency/coastal-realty",
  },
  referral: {
    role: "referral_partner",
    email: "james@parkbusiness.com.au",
    name: "James Park",
    company: "Park Business Consulting",
    icon: "🤝",
    accent: "amber",
    type: "Referral Partner",
    desc: "Refer clients, earn 20% of every service for 12 months. Automatic.",
    loginTitle: "Referral Portal",
    loginSub: "Park Business Consulting · Commission tracking",
    cta: "Sign in to Referral Portal →",
    home: "/referral/dashboard",
  },
  direct: {
    role: "direct_client",
    email: "marcus@techcore.com",
    name: "Marcus Reid",
    company: "TechCore SaaS",
    icon: "🏗️",
    accent: "green",
    type: "Direct Client",
    desc: "Order directly from nexxtt.io — track projects, approve deliverables.",
    loginTitle: "Direct Client Portal",
    loginSub: "TechCore SaaS · Order direct from nexxtt.io",
    cta: "Sign in to Direct Portal →",
    home: "/direct/dashboard",
  },
  admin: {
    role: "admin",
    email: "riya@nexxtt.io",
    name: "Riya Tanaka",
    company: "nexxtt.io HQ",
    icon: "🛡️",
    accent: "adm",
    type: "Platform Admin",
    badge: "Super Admin",
    desc: "Master control of every portal — agencies, clients, referrals, orders, finance.",
    loginTitle: "Admin Portal",
    loginSub: "nexxtt.io HQ · Super Admin access",
    cta: "Sign in to Admin Portal →",
    home: "/admin",
  },
};

export const DEMO_COOKIE = "nexxtt-demo-role";
